apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  # unique name per namespace for the template
  name: create-gel-component
  # title of the template
  title: Create GEL Component
  # a description of the template
  description:
    Boilerplate for creating a GEL component
  # some tags to display in the frontend
  tags:
    - component
    - gel
spec:
  # which templater key to use in the templaters builder
  templater: cookiecutter
  # what does this template create
  type: component
  # if the template is not in the current directory where this definition is kept then specify
  path: 'component_id'
  # the schema for the form which is displayed in the frontend.
  # should follow JSON schema for forms: https://jsonforms.io/
  schema:
    required:
      - component_id
      - description
    properties:
      component_id:
        title: Component Name
        type: string
        description: Unique name of the component
      description:
        title: Description
        type: string
        description: Description of the component
