apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gel-component
  description: GEL Component that does stuff
  annotations:
    backstage.io/techdocs-ref: value
spec:
  type: service
  lifecycle: experimental
  owner: web-presentation-layer
  system: web-core-services
